# Programación y NumPy

En la primera parte de este notebook seguiremos explorando algunas cuestiones de programación. En la segunda parte, empezaremos a trabajar con NumPy, nuestra primera librería.

## 1. Programación

### 1.1 Operaciones Lógicas

Comencemos viendo cómo implementar lo que vimos en la bitácora de operaciones lógicas. Te recomendamos tener la bitácora cerca así puedes consultarla.

En primer lugar, la operación `not` es simplemente la negación del booleano.

In [1]:
variable_1 = True
print(not(variable_1))

variable_2 = False
print(not(variable_2))

False
True


La operación `and` nos devuelve `True` unicamente cuando ambas variables son verdaderas. Experimentar con la celda inferior y comprobar su tabla de verdad.

In [2]:
variable_1 = True
variable_2 = False
print(variable_1 and variable_2)

False


**Ejercicio:** comprobar la tabla de verdad de la operación `or` jugando con la celda siguiente. Viene con trampa(s).

In [3]:
A = False
C = False
A_or_B = variable_1 or variable_2
print(A_or_B)

True


### 1.2 Estructuras de control - Condicionales

Los condicionales nos permiten ejecutar o no un bloque de codigo dependiendo de ciertas condiciones. En lenguaje coloquial, vendrían a ser del estilo de "Si se cumple esta condición, hace A. Si no se cumple, hace B", donde B puede ser, simplemente, no hacer nada. Veamos qué formas toman.

### 1.2.1 If

El condicional más simple es el `if`. Para mayor claridad escribiremos la condicion entre parentesis (), aunque esto no es necesario. Su estructura es 

``` python
if condicion:
    Si se cumple la condición, se ejecutan estas líneas de código
```

Veamos algunos ejemplos:

In [4]:
valor = 15
if (valor > 10):
    print('El valor es mayor que 10')

El valor es mayor que 10


Prestar atención a que la condición debe ser un booleano

In [5]:
print(valor > 10)
print(type(valor > 10))

True
<class 'bool'>


**Nota:** para comparar variables, tenemos las operaciones menor `<`, mayor `>`, igualdad `==`, menor o igual  `<=`, y mayor o igual `>=`.

In [28]:
print(3 == 3)
print(3 < 4)
print(5 > 3)
print(3 <= 3)
print(3 >= 3)

True
True
True
True
True


In [33]:
a = 'hola'
b = 'chao'

In [34]:
a > b

True

### 1.2.2 If, Else

A la estrucutra con `if` se le puede agregar otro bloque de codigo que se ejecute si la condición exigida NO se cumple. Esto se logra mediante la expresión `else`.

``` python
if condicion:
    Si se cumple la condición, se ejecutan estas líneas de código
else:
    Si NO se cumple la condición, se ejecutan estas líneas de código
```

In [37]:
nombre = 'Pedro'

if (nombre == 'Juan'):
    print('Esta persona se llama Juan')
else:
    print('Esta persona NO se llama Juan')

Esta persona NO se llama Juan


Prestar atención, nuevamente, a que la condición - lo que está entre paréntesis - es un booleano.

In [8]:
'Juan'=='Pedro'

False

### 1.2.3 If, Elif, Else
A esta estructura se le pueden sumar tantas condiciones encadenadas como uno desee, mediante la expresión `elif`. El orden en que se van chequeando las condiciones depende de su posición, priemero se chequea el `if`, luego el primer `elif`, luego el segundo, y así sucesivamente.

``` python
if condicion_1:
    Si se cumple la condicion_1 , se ejecutan estas líneas de código
elif condicion_2:
    Si se cumple la condicion_2 , se ejecutan estas líneas de código
elif condicion_3:
    Si se cumple la condicion_3 , se ejecutan estas líneas de código
else:
    Si NO se cumple ninguna de las condiciones anteriores, se ejecutan líneas celdas de código
```


In [38]:
edad = 20

if (edad < 18):
    print('Esta persona tiene menos de 18 años')
elif (edad > 18):
    print('Esta persona tiene mas de 18 años')
else:
    print('Esta persona tiene justo 18 años')

Esta persona tiene mas de 18 años


In [57]:
edad = 61

if (edad < 10):
    print('es un niño')
elif (edad < 18):
    print('es un adolescente')
elif (edad < 60):
    print('es un adulto')
else:
    print('es un anciano')

In [53]:
if (edad < 10):
    print('es un niño')
else:
    if (edad < 18):
        print('es un adolescente')
    else:
        if (edad < 60):
            print('es un adulto')
        else:
            print('es un anciano')

es un adolescente


In [47]:
if (edad < 10):
    print('es un niño')
if (edad < 18):
    print('es un adolescente')
if (edad < 60):
    print('es un adulto')
else:
    print('es un anciano')

es un adolescente
es un adulto


In [49]:
mensaje = 'es un niño' if edad < 18 else 'es un adulto'

In [51]:
if edad < 18:
    mensaje = 'es un niño'
else:
    mensaje = 'es un adulto'
print(mensaje)

es un niño


In [ ]:
edad < 18 ? print('es un niño') : print('es un adulto')

**Ejercicio**: Escriba un bloque de código que, dado un número, imprima la frase "El numero es par" si el número es par o la frase "El numero es impar" si no lo es.

In [10]:
numero = 17
if numero%2==0:
    print('Es par')
else:
    print('Es impar')

Es impar


### 1.3 Combinando estructuras de código

Las estructuras de loops que vimos en la bitácora anterior y condicionales que aprendimos se pueden combinar para generar comportamientos más complejos. Supongamos que tenemos una lista de edades y nos queremos quedar con aquellas que sean mayores que 18 años. Podemos hacer lo siguiente:

In [11]:
lista_de_edades = [4,20,15,29,11,42,10,18]
lista_mayores = []

for edad in lista_de_edades:
    if (edad >= 18):
        # Agremos a la lista de mayores
        lista_mayores.append(edad)

print(lista_mayores)

[20, 29, 42, 18]


### 1.4 Operaciones lógicas y estructuras de control

A veces, queremos ejecutar una línea de código si se cumple más de una condición. Esto se puede lograr fácilmente usando las operaciones lógicas que vimos. Supongamos que tenemos una lista de números, y queremos seleccionar aquellos que cumplan ciertas propiedades. Por ejemplo, que son mayores o iguales que 5 y menores que 20. Podríamos hacer lo siguiente:

In [12]:
numeros = [0,3,1,4,6,17,3,89,5,6,4,13,25,4,3,23,1,15,2]
seleccionados = []
for numero in numeros:
    if numero >= 5:
        if numero < 20:
            seleccionados.append(numero)
print(seleccionados)

[6, 17, 5, 6, 13, 15]


Notar que los números seleccionados cumplen los requisitos que pedimos. Pero también podríamos hacerlo así:

In [13]:
numeros = [0,3,1,4,6,17,3,89,5,6,4,13,25,4,3,23,1,15,2]
seleccionados = []
for numero in numeros:
    if numero >= 5 and numero < 20:
        seleccionados.append(numero)
print(seleccionados)

[6, 17, 5, 6, 13, 15]


El resultado es el mismo. Si bien esta forma es más compacta, no necesariamente implica que sea mejor. Uno/a elije hacerlo de una u otra forma según lo que le parezca más claro; si ambas condiciones juntas son difíciles de leer, tal vez puedes usar la primera forma.

**Ejercicio**: Modifica el ejemplo anterior para que seleccione aquellos números **mayores** que 5 **o** impares.

In [14]:
numeros = [0,3,1,4,6,17,3,89,5,6,4,13,25,4,3,23,1,15,2]
seleccionados = []
for numero in numeros:
    if numero > 5 or numero%2 == 1:
        seleccionados.append(numero)
print(seleccionados)

[3, 1, 6, 17, 3, 89, 5, 6, 13, 25, 3, 23, 1, 15]


### Ejercitación

**Ejercicio 1**: ¿Qué pasa si sumás, restás, multiplicás o dividís booleanos? Pruébalo e interpreta.

In [15]:
print(True + True)
print(True + False)
print(False + False)
print(True - True)
print(True - False)
print(False - False)
print(True * True)
print(True * False)
print(False * False)
print(True / True)
print(True / False)
print(False / False)

2
1
0
0
1
0
1
0
0
1.0


ZeroDivisionError: division by zero

**Ejercicio 2**: Hacer una estructur `if/else` que compare dos variables numéricas `A` y `B` y que decida cuál es mayor e imprima en pantalla "A es mayor que B" o "B es mayor que A" . 

In [16]:
A = 3
B = 4
if A>B :
    print('A es mayor a B' )
else:
    print('B es mayor a A')

B es mayor a A


**Ejercicio 3 - Challenge**: Dada la siguiente lista de numeros:

In [21]:
import time

In [26]:
numeros = [4,5,1,3,5,7,8,1,3,4,1,7,8,1,3,4,5,2,1,2,4,5] * 100000000
nums = np.array(numeros)

Escribir una rutina que calcule la suma de los números **pares menores que 5** en esta lista. **Pistas:** 
* Hay muchas formas de hacerlo, si piensas en más de una, mejor. Pero trata de tomar los ejemplos que vimos en este notebook.
* El resultado es 20. 
* Recuerda que puedes inicializar una variable en cero, y luego ir modificándola en un loop. Hicimos algo así en el notebook de la bitácora anterior con una variable que llamamos `i` y en el ejercicio 5 del mismo notebook.

In [24]:
start = time.time()

suma = 0
for numero in numeros:
    if numero < 5 and numero % 2 == 0:
        suma = suma + numero
print(suma)

end = time.time()
print(f'tiempo de ejecución: {end - start}')

200000000
tiempo de ejecución: 21.20628833770752


In [20]:
start = time.time()

suma = 0
for numero in numeros:
    if numero < 5 and not numero % 2:
        suma += numero
print(suma)

end = time.time()
print(f'tiempo de ejecución: {end - start}')

20000000
tiempo de ejecución: 2.0601370334625244


In [21]:
start = time.time()

suma = sum(filter(lambda x: x < 5 and not x % 2, numeros))
print(suma)

end = time.time()
print(f'tiempo de ejecución: {end - start}')

20000000
tiempo de ejecución: 2.225005865097046


In [25]:
start = time.time()

numeros = [4,5,1,3,5,7,8,1,3,4,1,7,8,1,3,4,5,2,1,2,4,5] * 100000000
nums = np.array(numeros)
suma = np.extract((nums < 5) &  ~(nums % 2), nums).sum()
print(suma)

end = time.time()
print(f'tiempo de ejecución: {end - start}')

200000000
tiempo de ejecución: 5.291609048843384


In [27]:
start = time.time()

elevado = list()
for numero in numeros:
    elevado.append(numero ** 2)
#print(elevado)

end = time.time()
print(f'tiempo de ejecución: {end - start}')

tiempo de ejecución: 862.5959858894348


In [28]:
start = time.time()

elevado = np.power(nums, 2)
#print(elevado)

end = time.time()
print(f'tiempo de ejecución: {end - start}')

tiempo de ejecución: 124.51768708229065


In [29]:
start = time.time()

elevado = nums ** 2
#print(elevado)

end = time.time()
print(f'tiempo de ejecución: {end - start}')

tiempo de ejecución: 68.23077201843262


**Ejercicio 4 - Challenge Opcional**: Dada la siguiente lista de numeros:

In [1]:
numeros_en_texto = ['2', '3', '2', '3', '2', '2', '2', '2', '3', '2', '3', '1', '3', '1', '2', '2', '2', '2', '2', '2', '2', '2', '1', '2', '3', '2', '2', '2', '2', '1', '2', '3', '2', '2', '3', '2', '3', '3', '2', '2', '1', '3', '3', '2', '3', '2', '2', '1', '2', '1', '1', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '1', '2', '2', '3', '2', '2', '2', '2', '1', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '3', '2', '2', '3', '3', '1', '1', '3', '2', '1', '2', '2', '2', '1', '1', '2', '2', '2', '2', '2', '2', '2', '3', '3', '1', '3', '3', '3', '2', '2', '2', '2', '2', '2', '2', '3', '3', '2', '2', '3', '2', '2', '2', '2', '2', '3', '3', '2', '2', '1', '3', '2', '2', '2', '3', '2', '3', '1', '3', '3', '2', '3', '3', '2', '2', '2', '2', '2', '2', '1', '2', '2', '1', '2', '3', '2', '1', '3', '1', '2', '3', '3', '3', '2', '3', '1', '3', '2', '3', '1', '2', '2', '2', '3', '3', '2', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '2', '1', '2', '3', '1', '3', '2', '2', '3', '3', '3', '2', '2', '1', '1']
print(numeros_en_texto)

['2', '3', '2', '3', '2', '2', '2', '2', '3', '2', '3', '1', '3', '1', '2', '2', '2', '2', '2', '2', '2', '2', '1', '2', '3', '2', '2', '2', '2', '1', '2', '3', '2', '2', '3', '2', '3', '3', '2', '2', '1', '3', '3', '2', '3', '2', '2', '1', '2', '1', '1', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '1', '2', '2', '3', '2', '2', '2', '2', '1', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '3', '2', '2', '3', '3', '1', '1', '3', '2', '1', '2', '2', '2', '1', '1', '2', '2', '2', '2', '2', '2', '2', '3', '3', '1', '3', '3', '3', '2', '2', '2', '2', '2', '2', '2', '3', '3', '2', '2', '3', '2', '2', '2', '2', '2', '3', '3', '2', '2', '1', '3', '2', '2', '2', '3', '2', '3', '1', '3', '3', '2', '3', '3', '2', '2', '2', '2', '2', '2', '1', '2', '2', '1', '2', '3', '2', '1', '3', '1', '2', '3', '3', '3', '2', '3', '1', '3', '2', '3', '1', '2', '2', '2', '3', '3', '2', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '2', '1', '2', '3', '1',

Calcule la suma de los unos (1) y los tres (3) en esta lista. Nuevamente, hay muchas formas de hacerlo. **Pistas:** 
* El resultado es 210.
* Puede reciclar código de ejemplos anteriores y del ejercicio anterior.
* Se pueden comparar strings, ver ejemplo más arriba.
* También se pueden forzar tipos de datos. Por ejemplo, `int('4')` nos devuelve un 4, entero.
* Se puede resolver sin usar todas las pistas

In [4]:
### Les dejamos una de las formas mas compactas
suma = 0
for numero in numeros_en_texto:
    if numero == '1' or numero == '3':
        suma+=int(numero) # es equivalente suma = suma + numero
    
print(suma)

210


## 2. Numpy

Empezaremos a dar nuestros primeros pasos con NumPy. Es muy importante que googlees y consultes la documentación. Si no la instalaste, ahora es un buen momento.

Cuando queremos usar una librería, primero debemos importarla. Más adelante veremos qué significa importar una librería, pero podemos entenderlo como que es un aviso a Python de que vamos a incorporar nuevas funcionalidades; en este caso, desde NumPy.

In [6]:
import numpy as np

Ahora nuestro ambiente de trabajo sabe que si ponemos algo del estilo `np.` significa que esa funcionalidad la debe buscar en NumPy. **Importante:** Si la librería NO se instaló correctamente, te saltará un mensaje de error.

El principal tipo de dato sobre el que trabaja NumPy son los arreglos o arrays. Los arreglos son parecidos a listas y, de hecho, se pueden crear a partir de ellas.

In [7]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero son más que una lista. Algunas cosas que no se podían hacer con las listas ahora sí se pueden con arreglos. Recordemos que sumarle un número a toda la lista no estaba permitido

In [13]:
lista * 5

[0,
 1,
 2,
 3,
 4,
 5,
 0,
 1,
 2,
 3,
 4,
 5,
 0,
 1,
 2,
 3,
 4,
 5,
 0,
 1,
 2,
 3,
 4,
 5,
 0,
 1,
 2,
 3,
 4,
 5]

¡Pero ahora con los arreglos sí!

In [14]:
arreglo * 5

array([ 0,  5, 10, 15, 20, 25])

Esto simplifica mucho hacer cuéntas. Pero no es sólo sumar, también muchas otras operaciones:

In [17]:
print(arreglo - 5)
print(arreglo - 2)
print(arreglo * 4)
print(arreglo ** 2)

[-5 -4 -3 -2 -1  0]
[-2 -1  0  1  2  3]
[ 0  4  8 12 16 20]
[ 0  1  4  9 16 25]


In [18]:
np.power(arreglo, 2)

array([ 0,  1,  4,  9, 16, 25])

Comprobar que, salvo la multiplicación, ninguno estaba permitido en listas. ¿Qué hace la multiplicación en el caso de una lista?

### 2.1 Creación de arreglos

Si bien podemos crear arreglos a partir de listas, NumPy viene con muchas funciones para hacerlo. Veamos algunas.

Una muy utilizada es `np.arange()`. Consulta su documentación. Otra opción es que, en una celda de código, escribas `np.arange` y aprietes `shift` + `tab`. De esa forma, te aparecerá la ayuda.

Juega un poco con el ejemplo a continuación.

In [28]:
arreglo = np.arange(3,20,2)
print(arreglo)

[ 3  5  7  9 11 13 15 17 19]


In [111]:
list(range(1,10,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [112]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Ejercicio:** investiga y crea ejemplos con las siguientes funciones
* `np.linspace`. Presta particular atención a cómo se diferencia de `np.arange`.
* `np.zeros` y `np.ones`.

### 2.2 Shape de los arreglos

Los arreglos tienen muchos más propiedades que las listas. En particular, pueden tener más de un *eje* o dimensión. Veamos a qué nos referimos:

In [29]:
arreglo_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arreglo_2d)

[[1 2 3 4]
 [5 6 7 8]]


Notar que tiene dos filas y cuatro columnas. Podemos descubrir esto sin imprimirlo en pantalla, sino usando la propiedad `.shape` del arreglo.

In [30]:
print(arreglo_2d.shape)

(2, 4)


Primero aparece el número de filas y luego el de columnas. ¿Qué estructura de dato es `(2, 4)`? Otro ejemplo:

In [31]:
arreglo_2d = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arreglo_2d)
print(arreglo_2d.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


Si queremos saber cuántos elementos tiene, podemos usar `.size`

In [32]:
print(arreglo_2d.size)

8


### 2.3 Funciones que operan sobre arreglos

Los arreglos de NumPy incorporan un montón de funciones que operan sobre los arreglos. Veamos algunos ejemplos.

In [33]:
un_arreglo = np.array([-100,2,3,17,25,1,95])
print(un_arreglo.min())
print(un_arreglo.max())

-100
95


En el caso 2D, podemos pedir que estas funciones operen sobre todo el arreglo, o por ejes.



In [57]:
# No te preocupes si no entiendes lo que hace esta celda
arreglo_2d = np.arange(9)
np.random.shuffle(arreglo_2d)
arreglo_2d = arreglo_2d.reshape((3,3))
print(arreglo_2d)

[[4 7 5]
 [1 0 8]
 [2 3 6]]


Trata de entender la diferencia entre las siguientes instrucciones:

In [58]:
print(arreglo_2d.max())
print(arreglo_2d.max(axis = 0))
print(arreglo_2d.max(axis = 1))

8
[4 7 8]
[7 8 6]


### Últimos comentarios

* No dijimos nada sobre indexado ni slicing. Esto se debe a que, para arreglos 1D, es similar que para la listas. Para arreglos 2D, es apenas más complicado. Para estudiarlo, jugar con la siguiente celda:

In [61]:
arreglo_2d = np.arange(9).reshape(3,3)
print(arreglo_2d)
print(arreglo_2d[1,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4 5]


* Podemos usar `arreglo.max()` o `np.max(arreglo)`. Esto no es válido solamente para la función `max()`, sino también para casi todas las funciones que operen sobre arreglos. 

In [62]:
print(np.min(un_arreglo), un_arreglo.min())

-100 -100


Existe mucho más - realmente mucho más - para decir sobre NumPy. Pero mucho irá apareciendo a medida que lo vayamos necesitando. Y, además, ¡este notebook ya es muy largo!

### Ejercitación

**Ejercicio 1**: Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: `linspace`

In [63]:
arreglo = np.linspace(0,9,100)
print(arreglo)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

**Ejercicio 2:** crear un arreglo 1D de 20 ceros. Reemplazar los primeros 15 elementos por unos.

In [21]:
arreglo = np.zeros(20)
arreglo[:15] = 1
print(arreglo)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [39]:
arreglo = np.array([0] * 20)

In [33]:
arreglo[:15] = 1

In [42]:
arreglo.reshape(100,2)

ValueError: cannot reshape array of size 20 into shape (100,2)

In [36]:
arreglo[:]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [37]:
arreglo = 10

In [40]:
arreglo[:] = 10

In [41]:
arreglo

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10])

**Ejercicio 3:** crear un arreglo 1D de 50 ceros. Reemplazar los primeros 25 elementos por los números naturales del 0 al 24.

In [22]:
arreglo = np.zeros(50)
arreglo[:25] = np.arange(25)
print(arreglo)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


**Ejercicio 4:** crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la segunda columna por los números 1, 2 y 3 respectivamente. Es decir, crear la siguiente matriz:

```
0 1 0 
0 2 0
0 3 0
```

In [1]:
import numpy as np

In [3]:
arreglo = np.zeros((3,3))
arreglo[:,1] = np.arange(1,4)
print(arreglo)

[[0. 1. 0.]
 [0. 2. 0.]
 [0. 3. 0.]]


In [5]:
arreglo = np.zeros(9)
arreglo = arreglo.reshape(3,3)
arreglo[:, 1] = np.arange(1,4)
print(arreglo)

[[0. 1. 0.]
 [0. 2. 0.]
 [0. 3. 0.]]


In [7]:
np.eye(100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
print('a')

**Ejercicio 5:** crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la diagonal por unos. Es decir, crear la siguiente matriz:

```
1 0 0 
0 1 0
0 0 1
```

In [25]:
arreglo = np.zeros((3,3))
arreglo[0,0] = 1
arreglo[1,1] = 1
arreglo[2,2] = 1

print(arreglo)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Ejercicio 6:** crear un arreglo 2D de 100 filas y 100 columnas, lleno de ceros. Reemplazar los elemento de la diagonal por unos. Es decir, crear la siguiente matriz:

```
1 0 0 ... 0 0 0 
0 1 0 ... 0 0 0
0 0 1 ... 0 0 0
...  
0 0 0 ... 1 0 0
0 0 0 ... 0 1 0
0 0 0 ... 0 0 1
```

In [16]:
arreglo = np.zeros((100,100))
diag = np.arange(1,101)
for i in range(arreglo.shape[1]):
    arreglo[i,i] = diag[i]

arreglo[1,2] = 1000
print(arreglo)

[[   1.    0.    0. ...    0.    0.    0.]
 [   0.    2. 1000. ...    0.    0.    0.]
 [   0.    0.    3. ...    0.    0.    0.]
 ...
 [   0.    0.    0. ...   98.    0.    0.]
 [   0.    0.    0. ...    0.   99.    0.]
 [   0.    0.    0. ...    0.    0.  100.]]


In [24]:
d = np.diag(arreglo).copy()

In [25]:
d[:] = 1

In [26]:
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
diagonal = np.array([arreglo[i][i] for i in range(arreglo.shape[0])])

In [21]:
diagonal

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

**Extra:** ¿Qué tipo de dato está usando NumPy cuando crea los arreglos?¿Y si queremos cambiarle el tipo de dato, por ejemplo a `int`? Googlear "numpy astype". ¿Qué pasa si usamos `astype(bool)`?

In [114]:
locals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  "a = [1,2,'lala',True]",
  'import numpy as np',
  'b = np.array(a)',
  'b = np.array(a)',
  'b',
  'b + 1',
  "a = [1,2,'lala',True]\naa = [1,2,3,4]",
  'b = np.array(a)',
  'b',
  'b + 1',
  'b = np.array(a)\nbb = np.array(aa)',
  'b',
  'b + 1',
  'bb + 1',
  'any(bb)',
  'all(bb)',
  'c = [1,0,1]',
  'any(c)',
  'all(c)',
  'c = [True,False,True]',
  'any(c)',
  'all(c)',
  'numeros = [4,5,1,3,5,7,8,1,3,4,1,7,8,1,3,4,5,2,1,2,4,5]',
  'suma = 0\nfor numero in numeros:\n    if numero < 5 and numero%2 == 0:\n        suma = suma + numero\nprint(suma)',
  'x % 2',
  'x = 11\nx % 2',
  'x = 11\nx % 2 == 0',
  'x = 11\nnot (x % 2)',
  'x = 10\nnot (x % 2)',
  'x = 10\nnot (x !% 2)',
  'x = 10\nnot (x % 2)',
  'filt

In [115]:
a = True

In [116]:
b = False

In [122]:
any([a,z])

NameError: name 'z' is not defined

[True, False, True]

In [29]:
~ False

-1

In [30]:
~ True

-2

In [31]:
~10

-11

In [32]:
p = True
q = False
print(p or q)
print(p or not q)
print(p | ~ q)

True
True
-1


In [33]:
~True

-2

In [34]:
~False

-1

In [35]:
~-2

1