# Funciones y Namespaces


## 1. Funciones

Una función es un bloque de código que sólo corre cuando es llamado.

In [ ]:
def par_o_impar(numero):
    if numero %2 == 0:
        print('Es par')
    else:
        print('Es impar')

Notar que si ejecutamos la celda no ocurre nada apreciable. Si llamamos a la función

In [ ]:
par_o_impar

<function __main__.par_o_impar(numero)>

Python nos dice, de una forma no muy clara, que se trata de una función. Las funciones se llaman con paréntesis:

In [ ]:
par_o_impar()

TypeError: par_o_impar() missing 1 required positional argument: 'numero'

Y en este caso, arroja un error porque falta un argumento, `numero`. Las dos siguientes son equivalentes:

In [ ]:
par_o_impar(numero = 9)
par_o_impar(9)

Es impar
Es impar


Al tener un solo argumento, en este caso no hay mucho lugar a confusión, pero las funciones pueden tener muchos argumentos:

In [ ]:
def division(dividendo, divisor):
    print(dividendo/divisor)

Entonces podemos llamar a la función pasándole los argumentos en orden, o explicitando el valor de cada argumento:

In [ ]:
division(4,2)
division(divisor = 4, dividendo = 2)  #notar que asi no nos tenemos que preocupar por el orden

2.0
0.5


También, pueden tener argumentos *por default*, que si no explicitamos, toman un valor predefinido:

In [67]:
def division(dividendo, divisor = 2):
    return(dividendo/divisor)

In [56]:
division(9)
division(9, 3) 
division(dividendo = 9, divisor = 3) 
division(9, divisor = 3) 

4.5
3.0
3.0
3.0


In [68]:
res = division(9)

In [69]:
type(res)

float

In [71]:
res

4.5

In [72]:
None

### 1.1 `return`

Las funciones pueden devolver resultados

In [ ]:
def division(dividendo, divisor = 2):
    variable_auxiliar = dividendo/divisor
    return variable_auxiliar

In [ ]:
resultado_division = division(9,3)

In [ ]:
print(resultado_division)

3.0


Y, si lo necesitamos, podemos hacer que devuelvan más de un resultado

In [ ]:
def division_y_producto(numero_1,numero_2):
    div = numero_1/numero_2
    prod = numero_1*numero_2
    return div, prod

### Son equivalentes
# def division_y_producto(numero_1,numero_2):
#     return numero_1/numero_2, numero_1*numero_2

In [ ]:
resultados = division_y_producto(10,5)
print(resultados)

(2.0, 50)


Notar la diferencia

In [ ]:
resultado_1, resultado_2 = division_y_producto(10,5)
print(resultado_1, resultado_2)

2.0 50


### 2. Namespaces and Scope

Encontrar la diferencia entre las siguientes celdas:

In [28]:
def division(dividendo, divisor = 2):
    variable_auxiliar = dividendo/divisor
    return variable_auxiliar
print(division(50))
print(divisor)

25.0


NameError: name 'divisor' is not defined

In [29]:
divisor = 5
def division(dividendo):
    variable_auxiliar = dividendo/divisor
    return variable_auxiliar
print(division(50))
print(divisor)

10.0
5


In [38]:
divisor = 5
def division(dividendo, divisor = 2):
    global divisor
    variable_auxiliar = dividendo/divisor
    return variable_auxiliar
print(division(50))
print(divisor)

SyntaxError: name 'divisor' is parameter and global (<ipython-input-38-d32f99ea2f86>, line 3)

**Investigar:** ¿qué es una variable global?¿Y una variable loca?¿Qué es un Namespace?

### 3. Funciones Lambda (Anónimas)

Una función `lambda` es una forma conveniente de crear una función en una sola línea. También se las conoce como funciones anónimas, ya que no suelen tener nombre.

In [ ]:
lambda_division = lambda x,y: x/y
lambda_division(80,10)

8.0

Algunas características:
1. Pueden tener cualquier cantidad de argumentos, pero solo una expresión
1. No se les suele poner nombre como hicimos, de hecho es raro utilizarlas de esa forma.
1. No necesitan un `return`
1. Muy cómodas para crear funciones rápido.
1. En general, las veras combinadas con funciones como `map()`, `filter()`, `apply()`, `applymap()`, etc.

Existen algunas diferencias sutiles entre una función creada con `def` y una función lambda, pero para nuestros objetivos basta con saber que una función lambda es una forma rápida de crear funciones sencillas.

### 4. Documentando funciones

Cuando creemos funciones es conveniente documentarlas, así si volvemos meses después a nuestro código, o se lo compartimos a alguien, podemos entender qué hace sin tener que leer y entenderlo completamente. Es decir, de la misma forma que hacemos con muchas de las funciones de las librerías que venimos usando. Hay muchos formatos para documentar una función, pero en general incluyen: qué hace la función, cuales son sus argumentos, y cuáles son sus returns. A veces, también algún ejemplo mostrando cómo se usa. El grado de detalle depende del tiempo y de la complejidad de la función. Recomendamos siempre documentar las funciones, aunque sea de forma breve.

Dejamos un formato de documentación a modo de ejemplo. En general, se estila documentar en inglés, pero vamos a hacer una excepción.

In [ ]:
def division_y_producto(numero_1,numero_2):
    '''
    Dados dos numeros, devuelve su division
    y su producto.
    
    Arguments:
    numero_1 -- dividendo, primer multiplicando
    numero_2 -- divisor, segundo multiplicando
    
    Returns:
    div -- la division entre los dos numeros
    prod -- el producto entre los dos numeros
    '''
    
    div = numero_1/numero_2
    prod = numero_1*numero_2
    return div, prod

Notar que si ahora ponemos `help()` de nuestra función, devuelve la documentación que creamos.

In [ ]:
help(division_y_producto)

Help on function division_y_producto in module __main__:

division_y_producto(numero_1, numero_2)
    Dados dos numeros, devuelve su division
    y su producto.
    
    Arguments:
    numero_1 -- dividendo, primer multiplicando
    numero_2 -- divisor, segundo multiplicando
    
    Returns:
    div -- la division entre los dos numeros
    prod -- el producto entre los dos numeros



También, si usamos shift+tab como hacemos con las otras funciones de las librerías.

### Challenge

1. Crea una función que tome como entrada dos arreglos de Numpy. Luego, que chequee si tienen el mismo tamaño; si no es así, que imprima un mensaje indicando que no tienen el mismo tamaño. Si tienen el mismo tamaño, que haga las siguientes operaciones:
    1. Crear un nuevo arreglo con el resultado de las resta de los dos arreglos originales.
    1. Elevar al cuadrado ese arreglo.
    1. Sumar todos los elementos y dividir por la cantidad de elementos.
    1. Devuelva la raiz de ese resultado.


In [2]:
import numpy as np

def RMSE(arreglo_1, arreglo_2):
    if arreglo_1.size == arreglo_2.size:
        resta = (arreglo_1 - arreglo_2)**2
        suma = resta.sum()/resta.size
        return np.sqrt(suma)
    else:
        print('Error: no tienen el mismo tamaño')

Testeamos el resultados

In [3]:
np.random.seed(10)  # que hace esta linea?
arreglo_1 = np.random.randint(-10,10, 50)
arreglo_2 = np.random.randint(-10,10, 50)
print(arreglo_1)
print(arreglo_2)

[ -1  -6   5 -10   7   6   7  -2  -1 -10   0  -2  -6   9   6  -6   5   1
   1  -9  -2  -6   4   7   9   3  -5   3   9   3   2  -9  -6   8   3   1
   0  -1   5   8   6  -3   1   7   4  -3   1  -9 -10   2]
[ -5  -6  -3   8   2  -8  -2   5   3   5  -4   0   1   6   2 -10   7   5
   2  -2   0   3   1  -9   8   3  -2  -1  -5 -10   8  -7   6   8   6   4
   9   5   9   7   8   4   6   0   7 -10   7  -1   6  -1]


In [4]:
RMSE(arreglo_1, arreglo_2)

7.487322618933954

Debería dar como resultado 7.48732

In [ ]:
np.random.seed(10)  # que hace esta linea?
arreglo_1 = np.random.randint(-10,10, 25)
arreglo_2 = np.random.randint(-10,10, 50)
print(arreglo_1)
print(arreglo_2)

[ -1  -6   5 -10   7   6   7  -2  -1 -10   0  -2  -6   9   6  -6   5   1
   1  -9  -2  -6   4   7   9]
[  3  -5   3   9   3   2  -9  -6   8   3   1   0  -1   5   8   6  -3   1
   7   4  -3   1  -9 -10   2  -5  -6  -3   8   2  -8  -2   5   3   5  -4
   0   1   6   2 -10   7   5   2  -2   0   3   1  -9   8]


In [ ]:
RMSE(arreglo_1, arreglo_2)

Error: no tienen el mismo tamaño


Debería dar como resultado un mensaje indicando que no tienen el mismo tamaño.

2. Documentar brevemente la función creada.

### 5. Ejercitación - Generala

¡Vamos a jugar a la generala! Para los que no la conocen: es un juego de dados. En este juego tienes 3 tiradas y 5 dados para formar distintas combinaciones (escalera, full, etc). Después de cada tiro, puedes decidir cuántos y cuáles dados dejar en la mesa y cuáles volver a tirar. De esta forma, tienes tres tiradas para lograr alguna de las combinaciones. La combinación que más puntos te da es la generala, que se obtiene cuando los 5 dados devuelven el mismo número.

El jugador puede tomar decisiones y plantear una estrategia en este juego, pero la última palabra la tiene el azar. Un buen matemático podría calcular las probabilidades de cada combinación, e ir calculando cómo se modifican estas probabilidades a medida que va dejando - o no - dados sobre la mesa.

En nuestro caso, lo que haremos es simular una generala simplificada - el único objetivo es obtener la generala, cinco dados iguales. Para ello, programarás una serie de funciones que te ayudarán a jugar a este juego. Con estas funciones, podrás responder varias preguntas, entre ellas:

1. ¿Cuán probable es obtener una generala en la primera tirada?
1. ¿Cuán probable es obtener una generala con dos tiradas?
1. ¿Cuán probable es obtener una generala luego de las tres tiradas?
1. ¿Qué es más problable: obtener una generala con tres tiradas y cinco dados o cuatros tiradas y seis dados?

y las que se te ocurran. ¡Manos a la obra!

**Importante:** todas las funciones que te pedimos definir acá se resuelven en pocas líneas de código. NumPy y Google forman un gran equipo. Nosotros te dejamos casos de testeo para tus funciones. Resuélvelos con un/a compañero/a, recuerda pensar el problema (escribiéndolo en un papel, hablándolo con alguien) y luego programa. ¡Verás que no son tan difíciles!

**Importante dos:** este desafío fue propuesto por *Ernesto Mislej* en el grupo de Facebook *Data Science Argentina*.¡Recomendamos unirse a éste o a otro grupo sobre Ciencia de Datos!

1. Crea la función `tirar_n_dados`. Debe tomar como argumento por defecto `n = 5`, pero tiene que funcionar correctamente para otros valores de `n`.

In [5]:
def tirar_n_dados(n = 5):
    resultado = np.random.choice([1,2,3,4,5,6],n)
    return resultado

In [6]:
tirar_n_dados()

array([3, 5, 3, 2, 2])

2. Crea la función `es_generala`. Esta función toma como entrada los resultados de `tirar_n_dados` y devuelve `True` si es generala y `False` si no lo es.

In [7]:
def es_generala(resultados_n_dados):
    booleano = np.all(resultados_n_dados == resultados_n_dados[0])
    return booleano
    

In [8]:
### TESTEO UNO
array_de_prueba = np.array([2,5,5,5,6])
print(es_generala(array_de_prueba))

False


In [ ]:
### TESTEO DOS
for _ in range(10000):
    tirada_dados = tirar_n_dados(n = 5)
    if es_generala(tirada_dados):
        print(tirada_dados)

[6 6 6 6 6]
[2 2 2 2 2]
[6 6 6 6 6]
[3 3 3 3 3]


3. Crea una función `seleccionar_mayoria` que, dada una tirada de n dados, devuelve cuál es la moda de los resultados y con qué frecuencia. Dos consideraciones: 
    * Si los n resultados son distintos, es indistinto cuál valor devuelve.
    * Si hay más de un valor posible para devolver - por ejemplo, en la tira `[1, 1, 2, 2, 3]` -, es indistinto cuál valor elige.
    
    Tal vez te sirva saber que estas consideraciones se resuelven automáticamente si utilizas algunas herramientas de NumPy, como `np.unique()`, `np.argmax()` y alguna más.

In [ ]:
def seleccionar_mayoria(resultados_n_dados):
    unique, counts = np.unique(resultados_n_dados, return_counts=True)
    idx = np.argmax(counts)
    maximo = unique[idx]
    frecuencia = counts.max()
    return maximo, frecuencia

In [ ]:
# TESTEO UNO
array_de_prueba = np.array([1,1,1,5,5])
print(seleccionar_mayoria(array_de_prueba))
### Debería dar como resultado (1,3)

# TESTEO DOS
array_de_prueba = np.array([5,3,2,1,6])
print(seleccionar_mayoria(array_de_prueba))
### Debería dar como resultado (algun numero salvo el 4,1)

(1, 3)
(1, 1)


Acá la cosa se empieza a poner áspera, pero tampoco tanto. Veamos algunas situaciones:

* Supongamos que en una primera tirada obtienes como resultado `[1, 1, 2, 5, 3]`. En ese caso, te debes quedar con los dados `[1, 1]` y volver a tirar los otros tres dados. Si cuando tiras los tres dados obtienes tres valores iguales **distintos** de los que habías reservado, la mejor estrategia es quedarte con esos tres dados y volver a tirar los otros dos. 
* Supongamos que en una primera tirada obtienes como resultado `[1, 1, 2, 5, 3]`. En ese caso, te debes quedar con los dados `[1, 1]` y volver a tirar los otros tres dados. Si cuando tiras los tres dados obtienes `[1, 1, 5]` debes poder sumar a los dados que apartaste esos dos `1`.

Entonces:


4. Crea una función `jugar` tome como argumentos `n_tiradas` con argumento por defecto `3` y `dados_total` con argumento por defecto `5` y que, utilizando las funciones que definiste antes, juegue a la generala. La función debe devolver un arreglo con las n-tiradas realizadas y un índice indicando en qué tirada logró la generala si corresponde (si no logra la generala, debe devolver un valor que indique que no se logró la generala, ¿cuál se te ocurre?). 
    
    Te vamos a dejar un esqueleto bastante armado para esta función, pero si quieres arrancar desde cero, obviamente puedes hacerlo. Para completarlo, ten en cuenta que luego de cada tirada debes dejar algunos dados en la mesa, `dados_mesa`, y volver a tirar otros, `dados_nuevos`. La cantidad de dados nuevos que debes tirar se decide dinámicamente en cada ciclo del loop. Cuando decides qué dados deben quedar sobre la mesa, debes mirar tanto los dados que ya estaban sobre la mesa como los que acabas de tirar, `todos_dados`.

In [ ]:
def jugar(n_tiradas = 3, dados_total= 5):
    # Numero de dados a tirar inicialmente
    n_dados = dados_total 
    
    # Dados en la mesa inicialmente
    dados_mesa = np.array([]) 
    
    # Donde guardamos las tiradas
    tiradas = np.zeros((n_tiradas, dados_total)) # 
    
    # Numero de tirada exitosa
    tirada_exitosa = -1
    
    # Contamos cuantas tiradas hicimos hasta ahora
    contador_tiradas = 0
    
    while (contador_tiradas < n_tiradas) and tirada_exitosa == -1:
        # Tiramos los dados
        dados_nuevos = tirar_n_dados(n_dados)
        
        # Combinamos los dados recien tirados con los que ya estan en la mesa
        todos_dados = np.concatenate((dados_mesa, dados_nuevos))
        
        # Guardamos tirada
        tiradas[contador_tiradas,:] = todos_dados
        
        # Nos fijamos si es generala
        if es_generala(todos_dados):
            # Si es, modificamos el valor de tirada exitosa.
            # Esto debe cortar el loop.
            tirada_exitosa = contador_tiradas
        else:
            # Si no es generala, sigue tirando 
            # Se fija qué dados debe dejar en la mesa
            maximo, frecuencia = seleccionar_mayoria(todos_dados)
            dados_mesa = np.repeat(maximo, frecuencia)
            
            # Calcula cuántos dados volver a tirar
            n_dados = dados_total - frecuencia
        
        # Suma al contador de tiradas
        contador_tiradas +=1
    return tiradas, tirada_exitosa

In [ ]:
# TESTEO
for i in range(200):
    tiradas, tirada_exitosa = jugar(3, 5)
    if tirada_exitosa >=0:
        print(tiradas, tirada_exitosa)

[[1. 3. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]] 1
[[2. 2. 2. 4. 2.]
 [2. 2. 2. 2. 4.]
 [2. 2. 2. 2. 2.]] 2
[[6. 2. 6. 6. 4.]
 [6. 6. 6. 6. 2.]
 [6. 6. 6. 6. 6.]] 2
[[6. 6. 6. 6. 1.]
 [6. 6. 6. 6. 6.]
 [0. 0. 0. 0. 0.]] 1
[[4. 4. 1. 4. 5.]
 [4. 4. 4. 4. 4.]
 [0. 0. 0. 0. 0.]] 1
[[2. 2. 1. 5. 5.]
 [2. 2. 2. 4. 2.]
 [2. 2. 2. 2. 2.]] 2


¿Estás contento/a con el código?¿Está bien hecho?¿Se te ocurre alguna situación que no haya sido considerada o donde pueda fallar? Siempre es importante ser crítico con el código desarrollado (y con la metodología en general) en busca de puntos débiles. Siempre se puede programar mejor. De hecho, hay un montón de buenas costumbres cuando programamos funciones que hemos dejado de lado, como por ejemplo, chequear que a nuestra funciones les lleguen los argumentos correctos. Por ejemplo, si nuestra función debe recibir como argumento un arreglo de NumPy de cierto shape, no está demás chequearlo.

Ahora sí, es hora de jugar con estas funciones. Elije algunas de las preguntas e intenta responderla, o genera alguna propia y fíjate si lo que hicimos te sirve para responderla. Nosotros elegimos responder qué generala es más probable, si tres tiros y cinco dados o cuatro tiros y seis dados, que te la daremos junto con el resuelto de este notebook.

In [ ]:
### PUEDE LLEVAR MUCHO TIEMPO, REDUCIR EL N
N = 100000
cantidad_de_generalas_3_5 = 0
for i in range(N):
    tiradas, tirada_exitosa = jugar(3, 5)
    if tirada_exitosa >=0:
        cantidad_de_generalas_3_5 +=1

cantidad_de_generalas_4_6 = 0
for i in range(N):
    tiradas, tirada_exitosa = jugar(4, 6)
    if tirada_exitosa >=0:
        cantidad_de_generalas_4_6 +=1

In [ ]:
print(cantidad_de_generalas_3_5/N)
print(cantidad_de_generalas_4_6/N)

0.0469
0.0541


Por lo que parece más probable la generala con cuatro tiros y seis dados.

In [11]:
def hola(mensaje='hola', veces=1, **kwargs):
    print(kwargs['mensaje'])
    amplificado = mensaje * veces
    return amplificado

In [3]:
m = 'hey'
n = 3
m*n

'heyheyhey'

In [12]:
hola(2,'hey')

KeyError: 'mensaje'

In [21]:
def hola(**kwargs):
    print(kwargs['mensaje'])
    print(kwargs['veces'])
    amplificado = mensaje * veces
    return amplificado

In [22]:
hola(2,'hey')

TypeError: hola() takes 0 positional arguments but 2 were given

In [16]:
x

5

In [17]:
y

5

In [18]:
x=3

In [19]:
x

3

In [20]:
y

5

In [23]:
lista1 = [1,2,3,4,5]

In [24]:
lista1 + 1

TypeError: can only concatenate list (not "int") to list

In [34]:
def funcion(x, y=1):
    return x+y
a = map(funcion, lista1)

In [35]:
b = map(lambda x: x+1, lista1)

In [36]:
lista1

[1, 2, 3, 4, 5]

In [37]:
list(a)

[2, 3, 4, 5, 6]

In [38]:
list(b)

[2, 3, 4, 5, 6]

In [39]:
c = filter(lambda x: x > 2, lista1)

In [40]:
list(c)

[3, 4, 5]

In [41]:
import seaborn as sns

In [42]:
flores = sns.load_dataset('iris')

In [44]:
flores['suma_sepal'] = flores['sepal_length'] + flores['sepal_width']

In [73]:
def funcion_flores(row):
    if(row['petal_width'] < 1):
        print(row['sepal_length'] + row['sepal_width'])
    else:
        print(row['sepal_length'] - row['sepal_width'])

In [74]:
flores['nueva_col3'] = flores.apply(funcion_flores, axis=1)

8.6
7.9
7.9
7.699999999999999
8.6
9.3
8.0
8.4
7.300000000000001
8.0
9.100000000000001
8.2
7.8
7.3
9.8
10.100000000000001
9.3
8.6
9.5
8.899999999999999
8.8
8.8
8.2
8.399999999999999
8.2
8.0
8.4
8.7
8.6
7.9
7.9
8.8
9.3
9.7
8.0
8.2
9.0
8.5
7.4
8.5
8.5
6.8
7.6000000000000005
8.5
8.899999999999999
7.8
8.899999999999999
7.8
9.0
8.3
3.8
3.2
3.8000000000000003
3.2
3.7
2.9000000000000004
3.0
2.5000000000000004
3.6999999999999997
2.5
3.0
2.9000000000000004
3.8
3.1999999999999997
2.6999999999999997
3.6
2.5999999999999996
3.0999999999999996
4.0
3.0999999999999996
2.7
3.3
3.8
3.3
3.5000000000000004
3.5999999999999996
4.0
3.7
3.1
3.1
3.1
3.1
3.0999999999999996
3.3
2.4000000000000004
2.6
3.6
4.0
2.5999999999999996
3.0
2.9
3.0999999999999996
3.1999999999999997
2.7
2.8999999999999995
2.7
2.8000000000000003
3.3000000000000003
2.5999999999999996
2.9000000000000004
3.0
3.0999999999999996
4.1
3.4
3.5
4.6
2.4000000000000004
4.4
4.2
3.6
3.3
3.7
3.8
3.2
3.0
3.2
3.5
3.9000000000000004
5.1
3.8
3.7
2.8
4.9
3.599

In [75]:
flores

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     suma_sepal  nueva_col  nueva_col2 nueva_col3  
0           8.6        8.6         8.6       None  
1           7.9        7.9         7.9       None  
2           7.9        7.9         7.9       None  
3           7.7        7.7         7.7       None  
4           8.6        8.6         8.6       None  
..          ...        ...         ...        ...  
145         9.7        3.7         3.7       None  
146         8.8        3.8         3.8       None  
147         9.5        3.5         3.5       None  
148         9.6        2.8         2.8       None  
149         8.9        2.9         2.9       None  

[150 rows x 9 columns]

In [50]:
flores['nueva_col2'] = flores.apply(lambda row: row['sepal_length'] + row['sepal_width'] if row['petal_width'] < 1 else row['sepal_length'] - row['sepal_width'], axis=1)

In [51]:
flores

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     suma_sepal  nueva_col  nueva_col2  
0           8.6        8.6         8.6  
1           7.9        7.9         7.9  
2           7.9        7.9         7.9  
3           7.7        7.7         7.7  
4           8.6        8.6         8.6  
..          ...        ...         ...  
145         9.7        3.7         3.7  
146         8.8        3.8         3.8  
147         9.5        3.5         3.5  
148         9.6        2.8         2.8  
149         8.9        2.9         2.9  

[150 rows x 8 columns]

In [ ]:
condicion ? resultado_true : resultado_false

In [ ]:
resultado_true if condicion else resultado_false

In [ ]:
lambda row: row['sepal_length'] + row['sepal_width'] if row['petal_width'] < 1 else row['sepal_length'] - row['sepal_width']

In [52]:
def saludo(mensaje):
    return mensaje

In [53]:
saludo('hola')

'hola'

In [54]:
saludo

<function __main__.saludo(mensaje)>

In [18]:
i = 10

In [19]:
def reset_a():
    global a
    a = 0
    print(a)

In [20]:
a

10

In [22]:
reset_a()

10


In [16]:
a

0

In [95]:
def promedio1(lista):
    tamano = len(lista)
    suma = sum(lista)
    promedio = suma/tamano
    return promedio

In [96]:
def promedio2(lista):
    tamano = len(lista)
    suma = sum(lista)
    return suma/tamano

In [99]:
def promedio3(lista):
    return sum(lista)/len(lista)

In [100]:
promedio3(lista1)

3.0

In [101]:
promedio4 = lambda x: sum(x)/len(x)

In [104]:
promedio4('jajaja')

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [103]:
promedio5 = lambda x:

IndentationError: unexpected indent (<ipython-input-103-691792df48d2>, line 2)

In [ ]:
promedio_js = (lista) => {
    tamano = len(lista)
    suma = sum(lista)
    promedio = suma/tamano
    return promedio
    }

In [107]:
if = 1

SyntaxError: invalid syntax (<ipython-input-107-773eba7f7781>, line 1)

In [109]:
len = 10

In [112]:
len * (lista1)

[1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5]

In [44]:
def func1():
    print('func1')
    def func2():
        print('func2')
    return func2

In [45]:
a = func1()

func1


In [46]:
a()

func2


In [49]:
def primes_under_n(N):
    if N <= 1:
        return 0, list()
    if N == 2:
        return 1, [2]
    nums = range(3, N + 1)
    primes = [2]
    for num in nums:
        is_prime = True
        for prime in primes:
            if num % prime == 0:
                is_prime = False
                break
        if is_prime:
            primes.append(num)
    return len(primes), primes

In [90]:
def primes_under_n_2(N):
    return [x for x in range(2, N + 1) if [y for y in range(2, x) if x % y == 0] == []]

In [87]:
[x for x in range(2, N + 1)]

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

In [88]:
x = 10
[y for y in range(2, x) if x % y == 0]

[2, 5]

In [84]:
primes_under_n_3 = lambda N: [x for x in range(2, N + 1) if [y for y in range(2, x) if x % y == 0] == []]

In [94]:
N = -25
primes_under_n(N)

(0, [])

In [95]:
primes_under_n_2(N)

[]

In [86]:
primes_under_n_3(N)

[2, 3, 5, 7, 11, 13, 17]

In [66]:
N = 1000000
num, lista = primes_under_n(N)

In [53]:
from numpy import log

In [67]:
N / log(N)

72382.41365054197

In [56]:
import numpy as np

In [68]:
num

78498

In [89]:
[].isEmpty8

AttributeError: 'list' object has no attribute 'isEmpty8'

In [97]:
list(range(0,-10))

[]